### ISSUE TITLE
Probable errors in the makefile

### ISSUE THREAD

**Issue by rupipal** [rednafi/hook-slinger#73]
Hi,

Probably due to the fact that docker compose (v2) is still beta, I noticed the following:

~/hook-slinger$ make start_servers
docker compose up --build -d
make: docker: Permission denied
make: *** [makefile:96: start_servers] Error 127

~/hook-slinger$ sudo make start_servers
[sudo] password for user: 
docker compose up --build -d
unknown flag: --build
See 'docker --help'.

So,

Usage:  docker compose [OPTIONS] COMMAND
...
Options:
      --ansi string                Control when to print ANSI control characters
                                   ("never"|"always"|"auto") (default "auto")
      --compatibility              Run compose in backward compatibility mode
      --env-file string            Specify an alternate environment file.
  -f, --file stringArray           Compose configuration files
      --profile stringArray        Specify a profile to enable
      --project-directory string   Specify an alternate working directory
                                   (default: the path of the Compose file)
  -p, --project-name string        Project name

Commands:
  build       Build or rebuild services
.....

And

docker compose build --help
...
Options:
      --build-arg stringArray   Set build-time variables for services.
      --no-cache                Do not use cache when building the image
      --progress string         Set type of progress output (auto, tty, plain,
                                quiet) (default "auto")
      --pull                    Always attempt to pull a newer version of the image.
  -q, --quiet                   Don't print anything to STDOUT

Finally, this worked, after changing makefile.

$make start_servers
docker compose up #--build -d
[+] Running 7/7
 ⠿ redis Pulled                                                                  51.2s
   ⠿ 59bf1c3509f3 Pull complete                                                   5.0s
   ⠿ 719adce26c52 Pull complete                                                   5.0s
....

Also,
sudo make stop_servers
....
Total reclaimed space: 2.265GB
docker compose down -t 1
unknown shorthand flag: 't' in -t
...

Though, -t  seems a valid flag.

docker compose down --help
...
  -t, --timeout int       Specify a shutdown timeout in seconds (default 10)

However, when I remove the flag in
docker compose down #-t 1 
docker: 'compose' is not a docker command.

...

So, I issued 

~/hook-slinger$ docker compose down
[+] Running 5/5
 ⠿ Container hook-slinger-monitor-1  Removed                               0.3s
 ⠿ Container hook-slinger-worker-1   Removed                               0.2s
 ⠿ Container wh_app                  Removed                               0.3s
 ⠿ Container wh_redis                Removed                               0.3s
 ⠿ Network hook-slinger_default      Rem...                                0.1s

**Comment by rednafi** [comment]
Isn't reproducible.
